//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.UI;
public class PlayerResources : MonoBehaviour { 
	public Text foodText;
	public Text healthText;
	public Text moneyText;
	public Map map;
	// Use this for initialization
	void Start () {

	}
	
	// Update is called once per frame
	void Update () {
		getPlayerResources ();
	}
	void getPlayerResources(){
		foodText.text = map.player.playerFood.ToString();
		//healthText.text = map.player.playerHealth.ToString();
		moneyText.text = map.player.playerMoney.ToString();

	}
	 
}
